/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.tsx"],
    theme: {
        fontSize: {
          "xs": "9px",
          "sm": "12px",
          "base": "14px",
          "lg": "16px",
          "xl": "18px",
          "2xl": "20px",
        },
        borderRadius: {
          "none": "0",
          "sm": "4px",
          "default": "8px",
          "md": "12px",
          "lg": "14px",
          "full": "9999px",
        },
        padding: {
          0: "0px",
          xs: "4px",
          sm: "8px",
          base: "12px",
          lg: "16px",
          xl: "20px",
        },
        margin: {
          0: "0px",
          xs: "4px",
          sm: "8px",
          base: "12px",
          lg: "16px",
          xl: "20px",
        },
        colors: {
          blue: "#1C44AC",
          blue200: "#00389320",
          red: "#DC143C",
          red200: "#DC143C20",
          light: "#f7f7f7",
          dark: "#122D42",
          border: "#14141515",
          borderDark: "#14141530",
          lightPlus: "#eeeeee",
          darkPlus: "#141415",
          white: "#ffffff",
          black: "#000000",
        },
        width: {
          "1": '4px',
          "2": '8px',
          "3": '12px',
          "4": '16px',
          "5": '20px',
          "6": '24px',
          "7": '28px',
          "8": '32px',
          "9": '36px',
          "10": '40px',
          "11": '44px',
          "12": '48px',
          "100": "100%",
        },
        gap: {
          "none": "0px",
          "xs": "4px",
          "sm": "8px",
          "default": "12px",
          "md": "16px",
          "lg": "20px",
          "xl": "40px",
        },
        extends: {
          height: {
            "1": "100%",
          }
        }
    },
    plugins: [],
  };